name: Test
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions: {}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run typecheck
      - run: npm run build
      # Optional integration test of the action using a dedicated GitHub App.
      - id: create_token
        if: ${{ vars.TEST_GITHUB_APP_ID != '' }}
        uses: ./
        with:
          # The only required permission is `Repository permissions > Metadata: Read-only`.
          app_id: ${{ vars.TEST_GITHUB_APP_ID }}
          private_key: ${{ secrets.TEST_GITHUB_APP_PRIVATE_KEY }}
      - if: ${{ steps.create_token.outcome != 'skipped' }}
        run: node --eval "assert('${{ steps.create_token.outputs.token }}'.length > 0);"
      - run: npm run prettier -- --check
